PROXY_POOL_URL = 'http://127.0.0.1:5555/random'

VALID_STATUS = [200]

TIMEOUT = 10

REDIS_HOST = 'localhost'

REDIS_PORT = 6379
REDIS_PASSWORD = ''
REDIS_KEY = 'weixin'

MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASSWORD = ''
MYSQL_DATABASE = 'weixin'

MAX_FAILED_TIME = 20
KEYWORD = '风景'